repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.9
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
    - id: mypy
      files: ^server/src/
      additional_dependencies: [pydantic, fastapi, httpx, types-cachetools]
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
    - id: bandit
      args: ["-q", "-r", "server/src/cvrgpt_core", "server/src/cvrgpt_api"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: local
  hooks:
    - id: pytest-coverage
      name: pytest with coverage
      entry: bash -c "cd server && export PYTHONPATH=src && python -m pytest --cov=cvrgpt_api --cov-fail-under=9"
      language: system
      pass_filenames: false
      always_run: true
