services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    build: ./server
    environment:
      API_KEY: ${API_KEY:-changeme}
      CVRGPT_REDIS_URL: redis://redis:6379/0
      PYTHONPATH: src
    ports: ["8000:8000"]
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz', timeout=5)"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
