from abc import ABC, abstractmethod

class Provider(ABC):
    @abstractmethod
    async def search_companies(self, q: str, limit: int = 10) -> dict: ...
    @abstractmethod
    async def get_company(self, cvr: str) -> dict: ...
    @abstractmethod
    async def list_filings(self, cvr: str, limit: int = 10) -> dict: ...
    @abstractmethod
    async def get_latest_accounts(self, cvr: str) -> dict: ...
