name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          cd server
          pip install -r requirements.txt
          pip install pytest-cov
      
      - name: Run tests with coverage
        run: |
          cd server
          export PYTHONPATH=src
          export REDIS_URL=redis://localhost:6379
          python -m pytest --cov=cvrgpt_api --cov-report=xml --cov-report=term --cov-fail-under=9
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: github.event_name == 'push'
        with:
          file: server/coverage.xml
