name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          cd server
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy types-cachetools
      
      - name: Run ruff
        run: |
          cd server
          ruff check src/
      
      - name: Run mypy
        run: |
          cd server
          export PYTHONPATH=src
          mypy src/cvrgpt_api/
